baseURL = 'https://nova.spees.dev/'
languageCode = 'en-us'
title = 'nova spees'

# disable unused Hugo features
disableKinds = ['taxonomy', 'term', 'section']

[params]
description = 'Nova Spees is a five-year-old pitbull terrier.'

[markup.goldmark.renderer]
  # required to render embedded html in content pages
  # like the embedded twitter timeline
  unsafe = true 
