baseURL = 'https://nova.spees.dev/'
languageCode = 'en-us'
# used in <head> metadata, visible in browser tab
title = 'nova spees'

# disable unused Hugo features in this theme
disableKinds = ['taxonomy', 'term', 'section']

[params]
  # used in <head> metadata
  description = 'Nova Spees is a five-year-old pitbull terrier.'
  # used in <footer> content
  author = 'Team Nova'
  authorUrl = "https://github.com/spondrak/nova"
  # set to true to disallow search engines from indexing this page, used in <head>
  noindex = false

[markup.goldmark.renderer]
  # required to render embedded html in content pages
  # e.g. the embedded twitter timeline
  unsafe = true 
